<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        function demo() {
            let prm = new Promise((resolve, reject) => {

                setTimeout(() => {
                    //  console.log('settimeout');
                    //resolve('成功');
                    reject('失败');
                }, 1000);
            });

            return prm;
        }

        //当在promise内部调用了resolve()方法则触动的是promise对象的第一个then()对应的成功时回调函数，该成功时回调函数执行完成后默认是resolve状态，接着后面每个then()方法的成功时回调函数都被触发
        // demo().then((d) => {
        //     console.log(d, 1111);
        // }).then((d) => {
        //     console.log(d, 2222);
        // }).then((d) => {
        //     console.log(d, 3333);
        // }).catch((err) => {
        //     console.log(err, 33);
        // });

        //如果在promise内部调用了reject()方法时则触发第一个catch()对应的失败回调函数或then()方法中第二个参数对应的失败回调函数，而不会触发后面的catch()方法或then()方法中第二个参数对应的失败回调函数
        demo().then((d) => {
            console.log(d, 111);
        }).catch((err) => {
            console.log(err, 222);
        }).catch((err) => {
            console.log(err, 333);
        })
    </script>
</head>

<body>

</body>

</html>